### ISSUE TITLE
Initial proposal (big picture)

### ISSUE THREAD

**Issue by sandraros** [tricktresor/cute#1]
The database table ZCUTE_TECH is used to configure tables which may be edited with CUTE. The columns TYPENAME (key), <strike>DRIVER_CLASS</strike>.
- TYPENAME should be checked in order to not be able to edit a standard SAP table or a table created by other companies (not sure how to do it).
- <strike>DRIVER_CLASS is to be a class which inherits from ZIF_CUTE_DRIVER. If empty, the default class ZCL_CUTE_MAIN will be instantiated.</strike>

<strike>The authorization object ZCUTE_TECH is used to maintain table ZCUTE_TECH. Fields TABNAME, ACTVT (02,03).</strike>

The transaction code ZCUTE is used to start CUTE:
- Selection screen:
  - <strike>Button "Configuration". It's displayed if user is authorized to maintain table ZCUTE_TECH.</strike>
  - Screen field "Type Name".
  - Radio buttons "Edit" and "Show".
- Check that the table name is listed in table ZCUTE_TECH.
- Check that the user is authorized to maintain the table. I guess we could reuse the standard authorization objects S_TABU_DIS and S_TABU_NAM.

Principle of integrating CUTE in an existing screen:
- Define a screen with buttons Leave, Check, Save, and a container control to contain the ALV grid.
- PBO:
```
TRY.
    DATA(cute) = zcl_Cute_Main=>get_Instance( Type_Name ).
    cute->set_Container( container ).
    cute->show( ).
  CATCH zcx_Cute INTO DATA(lx_Cute).
    MESSAGE lx_Cute TYPE 'E'. " For example, not authorized to view the table.
ENDTRY.
```
- PAI:
```
CASE okcode.
  WHEN 'LEAVE'.
    IF cute->check_unsaved_data( ) = abap_true.
      " Popup question "save, discard, cancel leave?"
      " IF not discard THEN:
      "     IF save THEN cute->save( ).
      "     SET SCREEN 0.
    ENDIF.
  WHEN 'SAVE'.
    cute->save( ).
ENDCASE.
```

**Comment by sandraros** [comment]
I propose to keep editing this ticket by including your latest changes.

**Comment by tricktresor** [comment]
latest changes are updated in the wiki
https://github.com/tricktresor/cute/wiki

**Comment by sandraros** [comment]
Closed. Useless proposal.

**Comment by goreraks** [comment]
I would propose to resuse the existing registry TVDIR instead of creating new registries. Also when one generates the table maintenance for Table/View, it creates a Customizing object(transaction SOBJ) definition which is essential for Transport of customizing content.
