### ISSUE TITLE
BOOLEAN_FLG doesn't exist in NW 752 SP01 Trial

### ISSUE THREAD

**Issue by christianguenter2** [tricktresor/cute#13]
![image](https://user-images.githubusercontent.com/17437789/67107545-f22a6d80-f1cc-11e9-9ec2-e5c016f915d8.png)

**Comment by tricktresor** [comment]
do you have an alternative boolean rollname in minisap?

**Comment by sandraros** [comment]
You may use the data element `FLAG`, whose eponymous domain `FLAG` is 1 character long and has two possible values `' '` and `'X'`.

**Comment by larshp** [comment]
looking at Steampunk / ABAPinSAPCP, it typically uses data element `BOOLEAN` (which also exists in minisap)

**Comment by sandraros** [comment]
I think that `FLAG` is better because it has only 2 possible values, while `BOOLEAN` has weird values `X = true, - = false, space = unknown`. Selection screens automatically convert a parameter based on `FLAG` into a checkbox, maybe ALV has some kind of such evaluation.

**Comment by fabianlupa** [comment]
I tend to use `XFELD` for DDIC boolean components / types which also has the automatic checkbox conversion in TMG.

**Comment by tricktresor** [comment]
Changed to FLAG
