### ISSUE TITLE
Transportation of customizing entries

### ISSUE THREAD

**Issue by DennstedtB** [tricktresor/cute#14]
A Feature that will be needed - transportation of changed entries. 

Maybe we can set up on my [Transportation Repository](https://github.com/DennstedtB/Transport-Services) which should cover customizing transport requests. - I can have a look and test this and then we might can integrate this into this repo.

**Comment by tricktresor** [comment]
Very important! thanks!
Your project looks very promising! quite complicated but I think that is because of the test classes (injection, Facade)?
Maybe simple use of function module TR_OBJECT_INSERT is sufficient?

**Comment by DennstedtB** [comment]
Yep, without the tdd process it would be way less complicated. ( did the open sap course a few weeks before and wanted to build it just like they did ^^) 
Tomorrow I should have the chance to have a look and build a small (and more simple) class for reuse.

I would not like to use the FM directly in the application. It will be used by this class, but the logic would be more exchangeable if we use the class.

**Comment by tricktresor** [comment]
Thanks!
I will check next.
I have to add the APACK marker interface to make sure that your lib is linked to mine. 
Not sure if my system supports that already.

**Comment by DennstedtB** [comment]
I am not really sure if you need APACK here - I more or less  copied the important part of my Repository to this repository. So there is no dependency. 

If I understood APACK right it works only on Cloud ( does it? ) and only need to link dependencies to other repos. But I've added it directly here in the repo, so it should work.

**Comment by DennstedtB** [comment]
I'll close this issue, but we can continue the discussion.

**Comment by tricktresor** [comment]
sorry, didn't realise this. Yes, in this case we do not need APACK! thanks!
