### ISSUE TITLE
CUTE logo

### ISSUE THREAD

**Issue by sandraros** [tricktresor/cute#2]
Current logo is both square and angular, which maybe doesn't reflect something "cute".
Cute logo could be inspired from something like that (no authorization to publish this truncated image from original https://amazello.com/products/5d-diamond-painting-cute-cat-couple):
![image](https://user-images.githubusercontent.com/34005250/67082072-b1b0fc80-f198-11e9-8971-7f1600c7c6ea.png)

**Comment by tricktresor** [comment]
That's true.
Unfortunately I cannot design "cute" things or animals. I can only do lines and squares... ;(
I also at first sight thought about something like this:

![giraffe](https://cdn.pixabay.com/photo/2014/04/03/00/35/giraffe-308771_960_720.png)

![robot](https://cdn.pixabay.com/photo/2013/07/13/12/04/android-159109_960_720.png)

But that was too kittenish in my opinion.

It's really hard to have a logo that is simple on one hand and expressive and unique on the other hand.

fancy fonts also seemed too "cute" to me:
https://www.1001fonts.com/znikomitno24-font.html?text=CUTE&size=240
https://www.1001fonts.com/flavors-font.html?text=CUTE&size=240

You either need a good font which expresses the name properly or a simple font with a remarkable logo.

**Comment by tricktresor** [comment]
most important issue so far: reworked logo design
https://github.com/tricktresor/cute/blob/master/img/really-cute-logo.png

**Comment by sandraros** [comment]
I love it! :)

**Comment by tricktresor** [comment]
perfect! ;)
