### ISSUE TITLE
Close maintenance popup

### ISSUE THREAD

**Issue by DennstedtB** [tricktresor/cute#20]
not sure if I am completly lost, but if I try to close the maintenance popup it does not work. It simply does not close the popup.

**Comment by tricktresor** [comment]
My fault! it simply does not work. I just needed a container to display the splitter control since it didn't work with "screen0" anymore.
just click on the main dynpro and hit ESC to leave the transaction.
sorry for confusing!
It's still a prototype...

**Comment by DennstedtB** [comment]
No problem. I know that this is still a prototype - I should have made clear, that this issue is just something we need to work on in the future.

**Comment by tricktresor** [comment]
in future there will be a dynpro with a custom container. 
That was something natural for me, but you could of course not know that... 😄

**Comment by DennstedtB** [comment]
Ah okay, well then it's okay. 
Sure I couldn't know exactly what you were planning, but I kinda like the idea of the popup ( you can open several tables, but it does not affect the mode restriction ).
