### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by larshp** [tricktresor/cute#25]
Hi,
I get the following syntax errors, looks like the objects are not in the repo?

![image](https://user-images.githubusercontent.com/5888506/67740827-7b387480-fa17-11e9-9666-2eef5c5670bd.png)

**Comment by tricktresor** [comment]
I have renamed the exception and obiously forgot to adapt the usage... ;(
For dodo the APACK interface is missing.

will correct both after system upgrade.

**Comment by tricktresor** [comment]
added apack_manifest
corrected exception classes
