### ISSUE TITLE
Type "DD07VTAB" is unknown. Interface Section ZIF_CUTE_SOURCE_INFO

### ISSUE THREAD

**Issue by SimpleSim** [tricktresor/cute#28]
Hi
When installing this I get a syntax error in Interface Section ZIF_CUTE_SOURCE_INFO. Type "DD07VTAB" is unknown. We are running SAP_ABA 740 0021.

Many thanks
Simon

**Comment by tricktresor** [comment]
thanks for mentioning!
fixed; used dd07v_tab instead.
