### ISSUE TITLE
Cannot install cute because of dodo dependency

### ISSUE THREAD

**Issue by christianguenter2** [tricktresor/cute#29]
I cannot install cute because of dodo dependency, although dodo is installed.
![image](https://user-images.githubusercontent.com/17437789/80471204-62b40300-8943-11ea-9de3-d9be0568dc30.png)

I guess it's due to missing class in dodo implementing ZIF_APACK_MANIFEST.

**Comment by rjbhayani** [comment]
![image](https://user-images.githubusercontent.com/19501487/81175031-7ead4980-8fc0-11ea-84d3-79c5b935d92a.png)
Same with me

**Comment by tricktresor** [comment]
I added apack manifest to DODO.
Could you please check if it works now?

**Comment by christianguenter2** [comment]
Works for me now. Thanks for fixing.
